apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: k8swalski-prod

replicas:
- name: k8swalski
  count: 3

patchesStrategicMerge:
- deployment-patch.yaml
